name: csn
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - brotlipy=0.7.0=py37hb5d75c8_1001
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2020.12.5=ha878542_0
  - cairo=1.16.0=h18b612c_1001
  - certifi=2020.12.5=py37h89c1867_0
  - cffi=1.14.4=py37hc58025e_1
  - chardet=4.0.0=py37h89c1867_0
  - cryptography=3.3.1=py37h7f0c10b_0
  - cudatoolkit=10.1.243=h036e899_6
  - dlib=19.21.1=py37h2d24ad0_0
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.1=he4413a7_1000
  - freeglut=3.2.1=h58526e2_0
  - freetype=2.10.4=h7ca028e_0
  - gettext=0.19.8.1=h0b5b191_1005
  - glib=2.66.3=h9c3ff4c_1
  - graphite2=1.3.13=h58526e2_1001
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hc401514_3
  - icu=58.2=hf484d3e_1000
  - idna=2.10=pyh9f0ad1d_0
  - intel-openmp=2020.2=254
  - jasper=2.0.14=habb8e15_1
  - jpeg=9d=h36c2ea0_0
  - ld_impl_linux-64=2.35.1=hed1e6ac_0
  - libblas=3.9.0=3_openblas
  - libcblas=3.9.0=3_openblas
  - libffi=3.3=h58526e2_1
  - libgcc-ng=9.3.0=h5dbcf3e_17
  - libgfortran=3.0.0=1
  - libgfortran-ng=9.3.0=he4bcb1c_17
  - libgfortran5=9.3.0=he4bcb1c_17
  - libglib=2.66.3=h1f3bc88_1
  - libglu=9.0.0=he1b5a44_1001
  - libgomp=9.3.0=h5dbcf3e_17
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=3_openblas
  - libopenblas=0.3.12=pthreads_h4812303_1
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=9.3.0=h2ae2ef3_17
  - libtiff=4.1.0=h4f3a223_6
  - libuuid=2.32.1=h14c3975_1000
  - libvpx=1.7.0=h439df22_0
  - libwebp-base=1.1.0=h36c2ea0_3
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=hb55368b_3
  - lz4-c=1.9.2=he1b5a44_3
  - mkl=2020.2=256
  - ncurses=6.2=h58526e2_4
  - ninja=1.10.2=h4bd325d_0
  - numpy=1.19.4=py37h7e9df27_1
  - opencv=3.4.2=py37h6fd60c2_1
  - openssl=1.1.1i=h7f98852_0
  - pcre=8.44=he1b5a44_0
  - pip=20.3.1=pyhd8ed1ab_0
  - pixman=0.38.0=h516909a_1003
  - pthread-stubs=0.4=h36c2ea0_1001
  - py-opencv=3.4.2=py37hb342d67_1
  - pycparser=2.20=pyh9f0ad1d_2
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pysocks=1.7.1=py37he5f6b98_2
  - python=3.7.8=hffdb5ce_3_cpython
  - python_abi=3.7=1_cp37m
  - pytorch=1.4.0=py3.7_cuda10.1.243_cudnn7.6.3_0
  - readline=8.0=he28a2e2_2
  - requests=2.25.1=pyhd3deb0d_0
  - scipy=1.5.3=py37h14a347d_0
  - setuptools=49.6.0=py37he5f6b98_2
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.34.0=h74cdb3f_0
  - tk=8.6.10=hed695b0_1
  - urllib3=1.26.2=pyhd8ed1ab_0
  - wheel=0.36.1=pyhd3deb0d_0
  - xorg-fixesproto=5.0=h14c3975_1002
  - xorg-inputproto=2.3.2=h14c3975_1002
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxfixes=5.0.3=h516909a_1004
  - xorg-libxi=1.7.10=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.5=h6597ccf_2
prefix: /home/alex/anaconda3/envs/csn
